{"uuid": "fce39546-4c01-40f3-82b3-f5264cbb6581", "children": ["d4299a95-9149-490f-b8fb-e700f5b6f304"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x000001CB529CFDA0>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 72, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1741713995753, "stop": 1741714002433}], "start": 1741713995278, "stop": 1741714002458}], "start": 1741713995278, "stop": 1741714008272}