{"uuid": "1dedbb05-f546-4276-8e2a-c7ae4b6a0ace", "children": ["be84ef6c-5932-476a-ba33-158e30a79430"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x000001AEE0DB40D0>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 90, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1741860100884, "stop": 1741860108539}], "start": 1741860100713, "stop": 1741860108541}], "start": 1741860100713, "stop": 1741860108732}