{"uuid": "7ad718fd-8c84-4072-b83e-abe82087583b", "children": ["b987670a-37c2-41bf-95e1-876a5155ae2a", "e32fb094-0c5f-4a9b-8cd6-fa5a586507c4", "987626e9-5af4-4399-ad96-be2f22a4fb05"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x0000014F5F69C0D0>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 86, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1741862270354, "stop": 1741862279733}], "start": 1741862270134, "stop": 1741862279735}], "start": 1741862270134, "stop": 1741862332994}