{"uid":"957abff21237b780","name":"Add a Manual Item with Specified Quantity","fullName":"suits.test_orderflows.test_cash.test_openorder_cash.TestOpenOrderCash#test_manual_item_and_qty","historyId":"ac1f794a1d1088b1f11e8a62fbe508b3","time":{"start":1741861957084,"stop":1741861957108,"duration":24},"description":"Tests if a manual item can be added to the cart with a specified quantity.","descriptionHtml":"<p>Tests if a manual item can be added to the cart with a specified quantity.</p>\n","status":"failed","statusMessage":"AssertionError: assert \"Error is Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element'...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)\" is True\n +  where \"Error is Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element'...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)\" = manual_item()\n +    where manual_item = <logic.takeout_logic.Calculations object at 0x000001DFCF2078E0>.manual_item\n +      where <logic.takeout_logic.Calculations object at 0x000001DFCF2078E0> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001DFCF133760>.calc","statusTrace":"self = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001DFCF133760>\n\n    @allure.story(\"Manual Item Management\")\n    @allure.title(\"Add a Manual Item with Specified Quantity\")\n    @allure.description(\"Tests if a manual item can be added to the cart with a specified quantity.\")\n    def test_manual_item_and_qty(self):\n>       assert self.calc.manual_item() is True\nE       assert \"Error is Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element'...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)\" is True\nE        +  where \"Error is Message: An unknown server-side error occurred while processing the command. Original error: 'POST /element'...ata\\\\Roaming\\\\npm\\\\node_modules\\\\appium\\\\node_modules\\\\@appium\\\\base-driver\\\\lib\\\\basedriver\\\\commands\\\\find.ts:75:12)\" = manual_item()\nE        +    where manual_item = <logic.takeout_logic.Calculations object at 0x000001DFCF2078E0>.manual_item\nE        +      where <logic.takeout_logic.Calculations object at 0x000001DFCF2078E0> = <test_cash.test_openorder_cash.TestOpenOrderCash object at 0x000001DFCF133760>.calc\n\nsuits\\test_orderflows\\test_cash\\test_openorder_cash.py:50: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"appium_driver","time":{"start":1741861897604,"stop":1741861903616,"duration":6012},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false,"stepsCount":0},{"name":"login_once","time":{"start":1741861903617,"stop":1741861905555,"duration":1938},"status":"passed","steps":[{"name":"Performing User Login","time":{"start":1741861903754,"stop":1741861904943,"duration":1189},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false,"stepsCount":0},{"name":"Entering Passcode","time":{"start":1741861904943,"stop":1741861905552,"duration":609},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false,"stepsCount":0}],"attachments":[{"uid":"7bfb6ccb844fbf14","name":"Login Info","source":"7bfb6ccb844fbf14.txt","type":"text/plain","size":54}],"parameters":[],"attachmentsCount":1,"shouldDisplayMessage":false,"hasContent":true,"attachmentStep":false,"stepsCount":2},{"name":"setup_driver","time":{"start":1741861956827,"stop":1741861957083,"duration":256},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false,"stepsCount":0},{"name":"capture_screenshot_on_failure","time":{"start":1741861956827,"stop":1741861956827,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false,"attachmentStep":false,"stepsCount":0}],"afterStages":[{"name":"capture_screenshot_on_failure::0","time":{"start":1741861959279,"stop":1741861959289,"duration":10},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: 'GET /screenshot' cannot be proxied to UiAutomator2 server because the instrumentation process is not running (probably crashed). Check the server log and/or the logcat output for more details\n    at UIA2Proxy.command (C:\\Users\\rutwik\\AppData\\Roaming\\npm\\node_modules\\appium\\node_modules\\@appium\\base-driver\\lib\\jsonwp-proxy\\proxy.js:350:13)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.getScreenshot (C:\\Users\\rutwik\\.appium\\node_modules\\appium-uiautomator2-driver\\lib\\commands\\screenshot.js:42:5)\n","statusTrace":"  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 126, in capture_screenshot_on_failure\n    appium_driver.get_screenshot_as_file(screenshot_path)  # Take screenshot\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 969, in get_screenshot_as_file\n    png = self.get_screenshot_as_png()\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1003, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1013, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\appium\\webdriver\\errorhandler.py\", line 125, in check_response\n    raise exception_class(msg=message, stacktrace=format_stacktrace(stacktrace))\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":0},{"name":"appium_driver::0","time":{"start":1741861965996,"stop":1741861966312,"duration":316},"status":"broken","statusMessage":"KeyboardInterrupt\n","statusTrace":"  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 67, in appium_driver\n    driver_instance.stop_driver()\n  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 49, in stop_driver\n    self.driver.quit()\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 589, in quit\n    self.execute(Command.QUIT)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 427, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 404, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 428, in _request\n    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\urllib3\\_request_methods.py\", line 135, in request\n    return self.request_encode_url(\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\urllib3\\_request_methods.py\", line 182, in request_encode_url\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\urllib3\\poolmanager.py\", line 443, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\urllib3\\connectionpool.py\", line 787, in urlopen\n    response = self._make_request(\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\urllib3\\connectionpool.py\", line 534, in _make_request\n    response = conn.getresponse()\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\site-packages\\urllib3\\connection.py\", line 516, in getresponse\n    httplib_response = super().getresponse()\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\http\\client.py\", line 1375, in getresponse\n    response.begin()\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\http\\client.py\", line 318, in begin\n    version, status, reason = self._read_status()\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\http\\client.py\", line 279, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"C:\\Users\\rutwik\\miniconda3\\envs\\automation\\lib\\socket.py\", line 717, in readinto\n    return self._sock.recv_into(b)\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true,"attachmentStep":false,"stepsCount":0}],"labels":[{"name":"Module","value":"Order Management"},{"name":"feature","value":"Open Order Flow - Cash Payment"},{"name":"story","value":"Manual Item Management"},{"name":"Type","value":"Functional Test"},{"name":"parentSuite","value":"suits.test_orderflows.test_cash"},{"name":"suite","value":"test_openorder_cash"},{"name":"subSuite","value":"TestOpenOrderCash"},{"name":"host","value":"LAPTOP-KKMKONCC"},{"name":"thread","value":"9524-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"suits.test_orderflows.test_cash.test_openorder_cash"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":true,"retry":true,"extra":{"categories":[],"tags":[]},"source":"957abff21237b780.json","parameterValues":[]}