{"uuid": "b26411ef-9be0-4111-ab66-17c4f91edd1c", "children": ["e7ce8620-773d-4f2a-81a4-30b296d127ef"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x000001EFFA809FC0>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\Automation-logic\\conftest.py\", line 92, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1743688467376, "stop": 1743688474067}], "start": 1743688467252, "stop": 1743688474068}], "start": 1743688467252, "stop": 1743688578060}