{"name": "Process a card refund", "status": "failed", "statusDetails": {"message": "AssertionError: assert \"Could'nt save the refund\" == True", "trace": "self = <test_takeoutorder_card.TestTakeOutFlow object at 0x00000212730B0130>\n\n    @allure.story(\"Refund Processing\")\n    @allure.title(\"Process a card refund\")\n    def test_refund(self):\n        refunded = self.calc.card_refund()\n>       assert refunded == True\nE       assert \"Could'nt save the refund\" == True\n\nAutomation-logic\\suits\\test_orderflows\\test_card\\test_takeoutorder_card.py:104: AssertionError"}, "start": 1743602527460, "stop": 1743602563679, "uuid": "dbe768f7-9250-4360-8df7-8354767340f8", "historyId": "ac4ce0fb8b7c3b28c133bc2c87cda0be", "testCaseId": "ac4ce0fb8b7c3b28c133bc2c87cda0be", "fullName": "suits.test_orderflows.test_card.test_takeoutorder_card.TestTakeOutFlow#test_refund", "labels": [{"name": "epic", "value": "Orderflow"}, {"name": "story", "value": "Refund Processing"}, {"name": "feature", "value": "Takeout order in Card"}, {"name": "parentSuite", "value": "suits.test_orderflows.test_card"}, {"name": "suite", "value": "test_takeoutorder_card"}, {"name": "subSuite", "value": "TestTakeOutFlow"}, {"name": "host", "value": "LAPTOP-KKMKONCC"}, {"name": "thread", "value": "11684-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "suits.test_orderflows.test_card.test_takeoutorder_card"}]}