{"uuid": "0278e250-e6b9-4090-b68b-4ce4556f27ef", "children": ["a0de8f84-a397-484d-acbf-4f696a0be45f"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x0000020D83CA8160>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 86, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1741882831973, "stop": 1741882838268}], "start": 1741882831826, "stop": 1741882838270}], "start": 1741882831826, "stop": 1741882849857}