{"uuid": "dabb2aa2-2ad2-479e-8e89-a577707d12a8", "children": ["21f9ee2f-e3a3-49ca-8fb7-4453ca8d6596"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x00000268196D5850>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 86, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1742290150713, "stop": 1742290157938}], "start": 1742290150516, "stop": 1742290157940}], "start": 1742290150516, "stop": 1742290189419}