{"uuid": "129f881d-093a-4089-9d67-4a1e447ce025", "children": ["a9345fed-2602-4b48-82ce-ddb49da8117b"], "befores": [{"name": "login_once", "status": "passed", "steps": [{"name": "Performing User Login", "status": "failed", "statusDetails": {"message": "AssertionError: Login failed.\nassert False is True\n +  where False = login()\n +    where login = <logic.login_logic.Login object at 0x000001C12CAA00D0>.login\n", "trace": "  File \"C:\\Users\\rutwik\\Automation\\conftest.py\", line 86, in login_once\n    assert testLogin.login() is True, \"Login failed.\"\n"}, "start": 1741885759557, "stop": 1741885759576}], "start": 1741885759430, "stop": 1741885759577}], "start": 1741885759430, "stop": 1741885760359}